####################
# Networking       #
####################
CONFIG_NETWORKING=y
CONFIG_NET_IPV6=n
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
#CONFIG_NET_ARP=y

# Get IPv4 address from DHCP
CONFIG_NET_DHCPV4=y
CONFIG_NET_CONFIG_AUTO_INIT=n
#CONFIG_NET_DHCPV4_OPTION_CALLBACKS=y
#CONFIG_DNS_RESOLVER=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y

# Generic networking options
#CONFIG_REQUIRES_FULL_LIBC=y

# Enable Ethernet
CONFIG_NET_L2_ETHERNET=y

# CoAP
CONFIG_COAP=y
CONFIG_COAP_SERVER=y
CONFIG_NET_CONFIG_SETTINGS=y

# Socket
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y
CONFIG_ZVFS_POLL_MAX=4

#CONFIG_COAP_SERVER_WELL_KNOWN_CORE=y
#CONFIG_COAP_WELL_KNOWN_BLOCK_WISE=n
#CONFIG_COAP_EXTENDED_OPTIONS_LEN=y
#CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=40


# Kernel options
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

####################
# LOGGING          #
####################
CONFIG_LOG=y
CONFIG_NET_LOG=y