####################
# Networking       #
####################
CONFIG_NETWORKING=y
CONFIG_NET_IPV6=n
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
#CONFIG_NET_ARP=y

# Get IPv4 address from DHCP
CONFIG_NET_DHCPV4=y
CONFIG_NET_CONFIG_AUTO_INIT=n
#CONFIG_NET_DHCPV4_OPTION_CALLBACKS=y
#CONFIG_DNS_RESOLVER=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y

# Generic networking options
#CONFIG_REQUIRES_FULL_LIBC=y

# Enable Ethernet
CONFIG_NET_L2_ETHERNET=y

# CoAP
CONFIG_COAP=y
CONFIG_COAP_SERVER=y
CONFIG_NET_CONFIG_SETTINGS=y

# Socket
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y
CONFIG_ZVFS_POLL_MAX=4

#CONFIG_COAP_SERVER_WELL_KNOWN_CORE=y
#CONFIG_COAP_WELL_KNOWN_BLOCK_WISE=n
#CONFIG_COAP_EXTENDED_OPTIONS_LEN=y
#CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=40


# Kernel options
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y


####################
# LVGL             #
####################
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=49152
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=16384
# it is one of the config variables that more RAM impact has
CONFIG_LV_Z_VDB_SIZE=10
# great for debugging
CONFIG_LV_USE_REFR_DEBUG=n

CONFIG_LV_USE_FLOAT=y

# Set RGB565
CONFIG_LV_COLOR_DEPTH_16=y

# Enabling Touch screen
CONFIG_INPUT=y

####################
# lv_conf.h macros #
####################
#CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
#CONFIG_LV_USE_BTN=y
CONFIG_LV_USE_IMAGE=y
#CONFIG_LV_USE_ARC=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_MONTSERRAT_30=y
# swap byte order
CONFIG_LV_COLOR_16_SWAP=n
# Aligns draw buffers to 4 bytes
CONFIG_LV_DRAW_BUF_ALIGN=4

####################
# LOGGING          #
####################
CONFIG_LOG=y
CONFIG_NET_LOG=y

CONFIG_REQUIRES_FLOAT_PRINTF=y
